dist: xenial

language: elixir

elixir:
  - 1.8.1
  - 1.7.4

otp_release:
  - 21.3
  - 20.3.3

env:
  global:
    - MIX_ENV=test
    - NODE_VERSION=10.15.3

before_install:
  - nvm install $NODE_VERSION

script:
  - npm install
  - mix coveralls
